name: etalia
description: A thesis project that display the value of nutrients that is connected to the hardware.
publish_to: 'none' 

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.5+1

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  percent_indicator: ^4.0.1
  firebase_core: ^2.10.0
  cloud_firestore:
  dashed_circular_progress_bar: ^0.0.4
  firebase_auth: ^4.5.0
  syncfusion_flutter_charts: ^21.2.3
  carousel_slider: ^4.2.1
  firebase_database: ^10.2.0
  weekday_selector: ^1.1.0
  shared_preferences: ^2.1.1
  ionicons: ^0.2.2
  notification_permissions: ^0.6.1
  flutter_local_notifications: ^14.1.0
  firebase_messaging:
  flutter_background_service: ^2.4.6
  flutter_background_service_android: ^3.0.3
  permission_handler: ^10.2.0
  flutter_launcher_icons: ^0.13.1

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/logo.png"

dev_dependencies:
  flutter_test:
    sdk: flutter
    
  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^2.0.0


# The following section is specific to Flutter packages.
flutter:

  uses-material-design: true

  assets:
      - assets/images/logo.png
      - assets/images/background.webp
      - assets/images/Prototype1.png
      - assets/images/Prototype2.png
      - assets/images/Prototype3.png
      - assets/images/Prototype4.png
      - assets/developer/No.jpg
      - assets/developer/Mary.jpg
      - assets/developer/Merily.jpg
      - assets/developer/Jamar.jpg
      - assets/developer/Karl.jpg
      - assets/developer/Justine.jpg
      - assets/icons/FertilizerBag.png
      - assets/icons/WateringCan.png

      

  fonts:
    - family: BrunoAce
      fonts:
      - asset: assets\fonts\BrunoAce-Regular.ttf
        weight: 300
    - family: Asul
      fonts:
      - asset: assets\fonts\Asul-Regular.ttf
        weight: 300
    - family: Tienne
      fonts:
      - asset: assets\fonts\Tienne-Regular.ttf
        weight: 300
      


